dataset:
  name: contrasted                       #name of the dataset
  nb_samples: 1200                      #number of samples to generate
  train_val_split: 1                 #training set proportion

  #objects path
  train_dir: ../objects/train/ 
  val_dir: ../objects/val/

point_cloud:
  generate: 0

scene:
  far: [3,4]
  near: [0.1,0.1]
  objects_distance: [0.55, 0.9]          #distance of objects (in meters) from camera

camera:
  resolution: [1024,1024]               #simulated camera resolution
  fov: [60,60]                          #simulated camera fov

image:
  resolution: [768,768]                 #output images resolution
  background_path: /home/ilias-m/Documents/DATASETS/LATIM/background_image/
  
objects: 
  Femur: 1
  Tibia: 0
  Tool: 1
  Tissue: 1


#configuration is saved in a yaml file so you can retrieve it later
save_conf_name: configs/demo.yaml

