!!omap
- dataset: !!omap
  - name: yaml_test
  - nb_samples: 100
  - train_val_split: 0.75
  - train_dir: ../objects/train/
  - val_dir: ../objects/val/
- camera: !!omap
  - resolution:
    - 1024
    - 1024
  - fov:
    - 60
    - 60
- image: !!omap
  - resolution:
    - 640
    - 640
  - background_path: /home/ilias-m/Documents/DATASETS/LATIM/background_images
- save_conf_name: configs/demo.yaml
