!!omap
- dataset: !!omap
  - name: contrasted
  - nb_samples: 1200
  - train_val_split: 1
  - train_dir: ../objects/train/
  - val_dir: ../objects/val/
- point_cloud: !!omap
  - generate: 0
- scene: !!omap
  - far:
    - 3
    - 4
  - near:
    - 0.1
    - 0.1
  - objects_distance:
    - 0.55
    - 0.9
- camera: !!omap
  - resolution:
    - 1024
    - 1024
  - fov:
    - 60
    - 60
- image: !!omap
  - resolution:
    - 768
    - 768
  - background_path: /home/ilias-m/Documents/DATASETS/LATIM/background_image/
- objects: !!omap
  - Femur: 1
  - Tibia: 0
  - Tool: 1
  - Tissue: 1
- save_conf_name: configs/demo.yaml
